
# Quantum State Anchoring Library Configuration

quantum_memory:
  memory_size: 10  # Maximum number of states to store in memory

error_correction:
  noise_threshold: 0.001  # Threshold for error correction algorithm

synchronization:
  sync_tolerance: 5  # Tolerance in seconds for time synchronization

logging:
  level: INFO  # Log level (DEBUG, INFO, WARNING, ERROR)
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
